[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] #ステータスライン
repo = 'itchyny/lightline.vim'

[[plugins]] #Spece Tabの可視化
repo = 'thinca/vim-zenspace'

[[plugins]] #インデントを可視化
repo = 'nathanaelkane/vim-indent-guides' 

[[plugins]] #括弧などの対応する文字を自動入力
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'
