"dein.vim dark power
let s:dein_dir = expand('~/.vim/bundle/')
let s:dein_repo_dir = s:dein_dir . 'repos/github.com/Shougo/dein.vim'

"dein Scripts-----------------------------
if &compatible
set nocompatible               " Be iMproved
endif

if !isdirectory(s:dein_repo_dir)
  echo "install dein.vim..."
  execute '!git clone git://github.com/Shougo/dein.vim' s:dein_repo_dir
endif
execute 'set runtimepath^=' . s:dein_repo_dir

" Required:
if dein#load_state(s:dein_dir)
  
  call dein#begin(expand('~/.vim/bundle'))
  let g:dein_dir = expand('~/.vim/bundle')
  let s:toml = g:dein_dir . '/dein.toml'

" Let dein manage dein
" Required:
  call dein#load_toml(s:toml, {'lazy': 0})

" You can specify revision/branch/tag.
  call dein#add('Shougo/vimshell', { 'rev': '3787e5' })

" Required:
  call dein#end()
  call dein#save_state()
endif

" Required:
filetype plugin indent on
syntax enable

" If you want to install not installed plugins on startup.
if dein#check_install()
  call dein#install()
endif

"End dein Scripts-------------------------

runtime! config/*.vim


